before_install: gem install bundler -v 1.12.5
gemfile:
  - gemfiles/as_5.0.gemfile
  - gemfiles/as_5.1.gemfile
  - gemfiles/as_5.2.gemfile
language: ruby
matrix:
  fast_finish: true
rvm:
  - 2.4
  - 2.5
  - 2.6
sudo: false
